spring.application.name=demo

# ==== Conexão com o banco ====
spring.datasource.url=jdbc:postgresql://localhost:5431/appdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

## ==== Pool de conexões (HikariCP, já vem com o Spring Boot) ====
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=2
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.idle-timeout=600000

# ==== JPA / Hibernate ====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
# Ativa o seed de dados de teste (data.sql) só localmente/dev
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ==== SQS (LocalStack)  ====
aws.sqs.endpoint=http://localhost:4566
aws.sqs.region=us-east-1
aws.sqs.fila-processa-pagamento-url=http://localhost:4566/000000000000/processa-pagamento.fifo
